### ISSUE TITLE
swarm v5.0.8 doesn't compile with dmd2.0.71 and dmdqproto14.1.1

### ISSUE THREAD

**Issue by don-clugston-sociomantic** [sociomantic-tsunami/swarm#313]
Does not compile with dmqproto v14.1.1 and dmd v2.0.71

./submodules/swarm/src/swarm/neo/client/RequestSet.d(430): Error: undefined identifier 'ProtocolError'

**Comment by nemanja-boric-sociomantic** [comment]
Template didn't compile in the unittests. v5.0.9 coming soon.
