### PR TITLE
Add missing import for ProtocolError

### LINKED ISSUE #313: swarm v5.0.8 doesn't compile with dmd2.0.71 and dmdqproto14.1.1
Does not compile with dmqproto v14.1.1 and dmd v2.0.71

./submodules/swarm/src/swarm/neo/client/RequestSet.d(430): Error: undefined identifier 'ProtocolError'

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
Add the import to the ProtocolError, since it's used in the RequestSet class.

Fixes #313

### CODE REVIEW

**Comment by don-clugston-sociomantic** [comment]
LGTM

**Comment by gavin-norman-sociomantic** [comment]
It's not clear why this code didn't fail in swarm / *proto before. Investigating...

**Comment by gavin-norman-sociomantic** [comment]
The reason is that swarm v4.6.x is not being compiled with dmd 2.071. So changes made in v4.6.x were not checked for 2.071 compatibility until they were merged into v5.0.x, which is tested with 2.071.
